<?php
/**
 * @file
 * Charts module integration with C3 library.
 */
use Drupal\charts_c3\Settings\CThree\ChartType;
use Drupal\charts_c3\Settings\CThree\CThree;
use Drupal\charts_c3\Settings\CThree\ChartTitle;

/**
* Implements hook_charts_info().
*/
function charts_c3_charts_info() {
    $info['c3'] = array(
        'label' => t('C3 Charts'),
        'types' => array('area', 'bar', 'column', 'line', 'pie', 'scatter'),
        );
    return $info;
}

function renderC3Charts($options, $categories = array(), $seriesData = array()){

    $c3Data = array();
    for($i = 0; $i < count($seriesData); $i++ ) {
        $c3DataTemp = $seriesData[$i]['data'];
        array_unshift($c3DataTemp, $seriesData[$i]['name']);
        array_push($c3Data, $c3DataTemp);
    }

    $c3Chart = new ChartType();
    $c3Chart->setType($options['type']);
    $c3ChartTitle = new ChartTitle();
    $c3ChartTitle->setText($options['title']);

    $c3 = new CThree();
    $c3->setChart($c3Chart);
    $c3->setLabels($options['data_labels']);
    $c3->setTitle($c3ChartTitle);
    $c3->setSeries($c3Data);

    $seriesColors = array();
    for ($i = 0; $i < count($seriesData); $i++) {
        $seriesColor = $seriesData[$i]['color'];
        array_push($seriesColors, $seriesColor);
    }

    $c3->setPattern($seriesColors);


    return $c3;
}
