<?php
/**
 * @file
 * Charts module integration with Google Charts library.
 */
use Drupal\charts_google\Settings\Google\GoogleOptions;
use Drupal\charts_google\Settings\Google\GoogleChartType;

/**
 * Implements hook_charts_info().
 */
function charts_google_charts_info() {
  $info['google'] = array(
    'label' => t('Google Charts'),
    'render' => '_charts_google_render',
    'types' => array('area', 'bar', 'column', 'line', 'pie', 'scatter'),
    'file' => 'charts_google.inc',
  );
  return $info;
}

/**
 * Creates a JSON Object formatted for Google charts to use
 * @param array $categories
 * @param array $seriesData
 * @return string
 */
function renderGoogleCharts($categories = array(), $seriesData = array()) {

    $dataTable = array();

    $dataTableHeader = array();
    for($r = 0; $r < count($seriesData); $r++ ) {
        array_push($dataTableHeader, $seriesData[$r]['name']);
    }

    for ($j = 0; $j < count($categories); $j++) {
        $rowDataTable = [];
        for ($i = 0; $i < count($seriesData); $i++) {
            $rowDataTabletemp = $seriesData[$i]['data'][$j];
            array_push($rowDataTable, $rowDataTabletemp);
        }
        array_unshift($rowDataTable, $categories[$j]);
        array_push($dataTable, $rowDataTable);
    }

    $dataTableHeader = array();
    for($r = 0; $r < count($seriesData); $r++ ) {
        array_push($dataTableHeader, $seriesData[$r]['name']);
    }

    array_unshift($dataTableHeader, 'label');
    array_unshift($dataTable, $dataTableHeader);

    return json_encode($dataTable);
}

function createGoogleChartsOptions($options){
    $googleOptions = new GoogleOptions();
    $googleOptions->setTitle($options['title']);

    return $googleOptions;
}
function createGoogleChartType($options){
    $googleChartType = new GoogleChartType();
    $googleChartType->setChartType($options['type']);

    return $googleChartType;
}
